name: nmrfilter
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.2
  - anaconda
  - rdkit
  - pytorch
  - torchvision
  - pandas
  - seaborn
  - scikit-learn
  - pyarrow
  - numba
  - click
  - pip
  - ipywidgets
  - pip:
    - igraph
    - ruffus
    - tqdm
    - networkx
    - tensorflow-cpu
    - tensorboardX
    - cirpy
    - pubchempy
    - louvain
